FROM node:22-alpine

WORKDIR /app

ARG DATABASE_URL
RUN npm install -g pnpm

COPY ./packages ./packages
COPY ./package.json ./pnpm-lock.yaml ./turbo.json ./
COPY ./turbo.json ./turbo.json
COPY ./apps/web/ ./apps/web/


COPY ./apps/web ./web

RUN pnpm install
RUN DATABASE_URL=${DATABASE_URL} pnpm run build
RUN pnpm run db:generate 

EXPOSE 3000

CMD [ "pnpm","run","start:web" ]