FROM node:22-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY ./packages ./packages
COPY ./package.json ./pnpm-lock.yaml ./turbo.json ./
COPY ./turbo.json ./turbo.json
COPY ./apps/ws-backend ./ws-backend


RUN pnpm install
RUN pnpm run db:generate 
RUN pnpm run build

EXPOSE 8080

CMD [ "pnpm","run","start:ws-backend" ]