FROM node:22-alpine

WORKDIR /app

ARG DATABASE_URL
RUN npm install -g pnpm

COPY . .
    
RUN pnpm install
RUN pnpm run db:generate
RUN DATABASE_URL=${DATABASE_URL} pnpm run build 

EXPOSE 3000

CMD [ "pnpm","run","start:web" ]